language: c
git:
  depth: false
  submodules: true
services:
  - docker
matrix:
  fast_finish: true
jobs:
  include:
    - stage: build
      script:
        - set -e
        - rm -rf build
        - ./cicd/run build
        - ./cicd/run test
        - ./cicd/run pack

deploy:
  provider: releases
  api_key:
    secure: "ibV25YFrLaRQxU8+q95AS/uM81ZlLjaBC1d0Pc2jJfqIF4nvEl0f1fcTWWqW4RjldcEC/7MEZCJ9IpOLDYyPiCcamfit7rBGidmrzzAOH31Sced7xj66pH64hnOh8BTFQaT1p5aeozPDokSlokvx1gNY8BeXah1fpXw7nTfXZe/RhSpHnsHYFO4ujHSWPbyejd9urRMfjI3VYNkhFyJ1RKTYRnJOwpKe8cqWgNp+fBybIfettAhbitPHO2KNMjxSh1B5XnnAt1hIhvtnS9VN78W2eMj9pAWFw/4OAF5z0HoAekcfPBfLx1RCan2eEct3KmKSygdB8ZMJ0RqgmfiCO9h/BZbXmCMnM/RVFFnXu5F87x9UVpM0k5GeWVlU+FXhzAfUEX5gLqnYJ0Fu8DuTZKirBaEtB5Ot5biT/OKNlDNAXDKBp/Z8Vb2SR05AwvVet/MzNhhyKLNwbMgEQ5wvTh6j/FcvZFNHep8GmGfFbj+HOlfCbz9uXq3vLitrNT0W4ZRzG8DuF9F0hzcxwDuNLoMoOwI4d7b+crHdwp/o7fFxRZ2IapRQaZl8lD7xpMZxOhto/k9IZBOheqX6xzTGTpYZaoWv5mECliiK0fCegq0Co8hQTrVFKkiu/8m66URDpbZj+w1BgKVF+Z2ZkqDF0AdAFD7zodVBb8/rTqsoUCI="
  file_glob: true
  file: build/assets/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
